"""initial schema

Materialises the current SQLAlchemy model state. Subsequent migrations should be
hand-written or autogenerated (`alembic revision --autogenerate`).

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-12
"""
from alembic import op

from app.database import Base
from app import models  # noqa: F401  (register all tables on Base.metadata)

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
