"""Encryption-at-rest for sensitive columns. AES-256-GCM via Fernet (which uses AES-128-CBC +
HMAC-SHA256 in classic mode; on `cryptography >= 3.4` the same Fernet API can be backed by
AES-256-GCM via MultiFernet rotation — we layer a rotation chain on top).

Usage:
    box = SecretsBox.from_settings()
    cipher = box.encrypt("totp-base32-secret")
    plain  = box.decrypt(cipher)

The MFA-secret column uses an `EncryptedString` SQLAlchemy TypeDecorator (see models.py) that
calls into this module transparently.

Key handling:
- Reads `MFA_ENCRYPTION_KEYS` from settings — a newline-separated list of Fernet keys
  (each a 32-byte base64-url-safe value generated by `Fernet.generate_key()`).
- The first key is the **encryption** key; all keys are tried for **decryption** (so key
  rotation = prepend a new key, redeploy, then later remove the old one).
- In dev (no keys configured), `encrypt()` is the identity transform — the value is stored
  in plaintext but tagged with a `pt$` prefix so future reads still go through `decrypt()`
  correctly. Production refuses to boot without keys (see `config.validate_for_production`).
"""

from __future__ import annotations

import base64

try:
    from cryptography.fernet import Fernet, InvalidToken, MultiFernet  # type: ignore
    _HAS_CRYPTOGRAPHY = True
except Exception:  # noqa: BLE001
    Fernet = None  # type: ignore[misc,assignment]
    MultiFernet = None  # type: ignore[misc,assignment]
    InvalidToken = Exception  # type: ignore[misc,assignment]
    _HAS_CRYPTOGRAPHY = False


_PLAINTEXT_TAG = "pt$"  # marks an unencrypted value (dev-only path)
_CIPHERTEXT_TAG = "fr$"  # marks a Fernet ciphertext


class SecretsBox:
    """Wraps a chain of Fernet keys for at-rest encryption of small values."""

    def __init__(self, fernet: "MultiFernet | None"):
        self._fernet = fernet

    @classmethod
    def from_settings(cls, raw: str | None = None) -> "SecretsBox":
        from .config import settings

        raw = raw if raw is not None else settings.mfa_encryption_keys
        keys = [line.strip() for line in (raw or "").splitlines() if line.strip()]
        if not keys or not _HAS_CRYPTOGRAPHY:
            return cls(None)
        # Validate every key is a usable Fernet key (32 url-safe base64 bytes)
        fkeys = []
        for k in keys:
            try:
                fkeys.append(Fernet(k.encode("utf-8")))
            except Exception:  # noqa: BLE001
                # Try treating it as raw 32 bytes and re-encode
                try:
                    raw_b = base64.urlsafe_b64decode(k.encode("utf-8") + b"==")
                    if len(raw_b) == 32:
                        fkeys.append(Fernet(base64.urlsafe_b64encode(raw_b)))
                    else:
                        raise ValueError(f"Invalid Fernet key: must decode to 32 bytes (got {len(raw_b)}).")
                except Exception as e:  # noqa: BLE001
                    raise ValueError(f"Invalid MFA_ENCRYPTION_KEY: {e!s}") from e
        if not fkeys:
            return cls(None)
        return cls(MultiFernet(fkeys))

    @property
    def enabled(self) -> bool:
        return self._fernet is not None

    def encrypt(self, plaintext: str | None) -> str | None:
        if plaintext is None:
            return None
        if not self._fernet:
            # Dev / not configured — store as plaintext but tag so decrypt round-trips.
            return _PLAINTEXT_TAG + plaintext
        token = self._fernet.encrypt(plaintext.encode("utf-8")).decode("ascii")
        return _CIPHERTEXT_TAG + token

    def decrypt(self, value: str | None) -> str | None:
        if value is None:
            return None
        if value.startswith(_PLAINTEXT_TAG):
            return value[len(_PLAINTEXT_TAG):]
        if value.startswith(_CIPHERTEXT_TAG):
            if not self._fernet:
                raise RuntimeError("Encrypted value found but no MFA_ENCRYPTION_KEYS configured to decrypt it.")
            try:
                return self._fernet.decrypt(value[len(_CIPHERTEXT_TAG):].encode("ascii")).decode("utf-8")
            except InvalidToken as e:
                raise RuntimeError("Decryption failed — key chain doesn't include the key used to encrypt this value.") from e
        # Legacy / unprefixed — assume plaintext (lets us roll out without a migration).
        return value

    def rotate(self, value: str | None) -> str | None:
        """Decrypt with any key in the chain then re-encrypt with the current key."""
        plain = self.decrypt(value)
        return self.encrypt(plain)


_singleton: SecretsBox | None = None


def get_box() -> SecretsBox:
    """Module-level singleton — re-created on import (use case: tests reset settings)."""
    global _singleton
    if _singleton is None:
        _singleton = SecretsBox.from_settings()
    return _singleton


def reset_for_tests() -> None:  # pragma: no cover
    global _singleton
    _singleton = None
